### PR TITLE
add Quantile open dp

### PR DESCRIPTION
**Pull request by Dhruv127**

### CODE REVIEW

**Comment by shobitnair** [comment]
Looking onto it !

**Comment by shobitnair** [comment]
Hey @Dhruv127  , please update tests/tools section to use your method for testing instead of diffprivlib.

**Comment by Dhruv127** [comment]
all tests passed

**Comment by shobitnair** [comment]
@Dhruv127  , I have tried testing it and it is failing in some test cases.
Please work out on the input_domain and metric for noise generator you are using to avoid the error.

**Pull request closed without merging**
